from .user import User
from .teaching_office import TeachingOffice
from .self_evaluation import SelfEvaluation
from .attachment import Attachment
from .manual_score import ManualScore
from .final_score import FinalScore
from .ai_score import AIScore
from .insight_summary import InsightSummary
from .sync_task import SyncTask
from .operation_log import OperationLog
from .college import College
from .improvement_plan import ImprovementPlan
from .anomaly import Anomaly
from .approval import Approval
